### ISSUE TITLE
gatsby theme

### ISSUE THREAD

**Issue by sw-yx** [madelyneriksen/gatsby-starter-tyra#13]
i loved this starter! needed a nice looking demo and found yours so i turned it into a theme. its yours if you want it, if not i'd be happy to maintain. https://github.com/sw-yx/gatsby-theme-netlify-identity/tree/master/gatsby-theme-tyra

**Comment by madelyneriksen** [comment]
Hey! Sorry, I have been really busy with work and am just now looking over this.

I think Gatsby themes are really cool, but they're something I'm not using quite yet so I wouldn't be comfortable maintaining it.

Also, thank you for the compliment :)
