### ISSUE TITLE
Mailchimp URL and Token in gatsby_config.js

### ISSUE THREAD

**Issue by ziyadbasheer** [madelyneriksen/gatsby-starter-tyra#189]
module.exports = {
  siteMetadata: {
   ....
    mailchimpUrl: ``,
    mailchimpToken: `b_f7f626ad1dc09f6d947b0d645_75aaf8bf95`,
  },

What are the exact values that we are expected to populate here?

Is the mailchimpUrl like this? https://listname.us20.list-manage.com/subscribe/post?u=23904u2093fj230fj&amp;id=203fk230f

How about the token? It says "hidden field" on mailchimp form, but what is the value?

The only field I found was this:

    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="049r304jg430gf20" tabindex="-1" value=""></div>

So I assume the value is under the "name" attribute? Please clarify. Thanks!

**Comment by madelyneriksen** [comment]
Hey!

To answer your questions:

1. The `mailChimpUrl` field is a URL that the form is both `POST`ed to AND that is linked in the navbar for signup. When you create a new embedded form on MailChimp, this is the "action" field of the HTML MailChimp shows you.

    This allows users to visit a signup page from a link as well as input their emails from your site directly!

2. The `token` is the `name` field of that hidden input, you're completely right!

Thanks for checking out Tyra! :smile:

**Comment by ziyadbasheer** [comment]
Thanks!
