### ISSUE TITLE
privacy page bug

### ISSUE THREAD

**Issue by slorber** [madelyneriksen/gatsby-starter-tyra#38]
https://gatsby-theme-netlify-identity.netlify.com/privacy

![image](https://user-images.githubusercontent.com/749374/63108613-97d01f00-bf87-11e9-8c12-c57e66beb1cf.png)

Great work anyway;) would have probably choosen this theme for my blog if MDX was supported (and if it was possible to make it less girly too :))

**Comment by madelyneriksen** [comment]
Thanks for bringing this up!! I've been swamped with work lately.

I'll take a look at adding in MDX because that sounds great from an editorial standpoint (carousels, lightboxes, etc.). However I think the style stays :)

**Comment by madelyneriksen** [comment]
Hi, I finally got a smattering of time to work on this and it's all fixed. Just a bad import statement for the SEO element. Thanks again for catching it!
