### ISSUE TITLE
404 Page 

### ISSUE THREAD

**Issue by M0nica** [madelyneriksen/gatsby-starter-tyra#9]
Currently there is no 404 page for this gatsby-starter. I'd like to work on creating one.

If this sounds good, do you have any suggestions for the content?

<img width="1120" alt="Screen Shot 2019-03-15 at 12 31 27 AM" src="https://user-images.githubusercontent.com/6998954/54408804-c2a50700-46b9-11e9-9cd2-10f8ecb7190d.png">

**Comment by madelyneriksen** [comment]
I'd be happy to accept a PR with a 404 page!

Content-wise I think a hero unit stating the error plus a link back to the homepage is a good idea.

**Comment by madelyneriksen** [comment]
Closing on account of #11!
